services:
  app:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - app_network

  nginx:
    container_name: nginx_server
    build: 
      context: ./nginx_server
      dockerfile: Dockerfile
    networks:
      - app_network
    ports: 
      - "80:8080"

networks:
  app_network:
    driver: bridge


